[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts",
  "forge-std/=lib/forge-std/src",
]

[rpc_endpoints]
goerli = 'https://rpc.ankr.com/eth_goerli'

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
